name: Continuous integration

on:
  pull_request:
  push:
    branches: [main, inertia-vue]

jobs:
  ci:
    uses: hosmelq/.github/.github/workflows/php-ci.yml@main
    with:
      php-version: "8.4"
